version: '2'
services:
    projet_taa_gli-app:
        image: projet_taa_gli
        external_links:
            - projet_taa_gli-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/projet_taa_gli?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    projet_taa_gli-mysql:
        extends:
            file: mysql.yml
            service: projet_taa_gli-mysql
